import { catalogUrl } from './config.js';
const $ = (s) => document.querySelector(s);
const audio = new Audio();
audio.preload = 'none';
let album, current = 0, language = 'en', loaded = false;
const copy = {en:{bio:'About the band',members:'Members',links:'Links',track:'Track',rights:'All rights reserved',error:'This track could not be played. Please try again.',play:'Play',pause:'Pause',previous:'Previous track',next:'Next track',seek:'Playback position',light:'Switch to light mode',dark:'Switch to dark mode'},it:{bio:'La band',members:'Componenti',links:'Link',track:'Brano',rights:'Tutti i diritti riservati',error:'Impossibile riprodurre questo brano. Riprova.',play:'Riproduci',pause:'Pausa',previous:'Brano precedente',next:'Brano successivo',seek:'Posizione di riproduzione',light:'Passa al tema chiaro',dark:'Passa al tema scuro'}};
const icon = {play:'M6 3v18l15-9z',pause:'M5 3h5v18H5zM14 3h5v18h-5z',previous:'M4 3h3v18H4zM20 3v18L8 12z',next:'M17 3h3v18h-3zM4 3v18l12-9z'};
const svg = (name) => `<svg viewBox="0 0 24 24" aria-hidden="true"><path d="${icon[name]}"/></svg>`;
const escape = (v) => String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const time = (s) => `${Math.floor((Number.isFinite(s)?s:0)/60)}:${String(Math.floor((Number.isFinite(s)?s:0)%60)).padStart(2,'0')}`;
function preference(key,value){try{if(value===undefined)return localStorage.getItem(key);localStorage.setItem(key,value);}catch{return null;}}
function safeUrl(value){const url=new URL(value,location.href);if(!['http:','https:'].includes(url.protocol))throw new Error('Unsupported URL');return url.href;}
function setTheme(theme){document.body.dataset.theme=theme;$('#theme').textContent=theme==='dark'?'☀':'☾';$('#theme').setAttribute('aria-label',copy[language][theme==='dark'?'light':'dark']);preference('recordplayer-theme',theme);}
setTheme(preference('recordplayer-theme') || (matchMedia('(prefers-color-scheme: light)').matches?'light':'dark'));
$('#theme').onclick=()=>setTheme(document.body.dataset.theme==='dark'?'light':'dark');
function details(){const c=copy[language];document.documentElement.lang=language;$('#bio-heading').textContent=c.bio;$('#members-heading').textContent=c.members;$('#links-heading').textContent=c.links;$('#bio').innerHTML=(album.bio[language]||album.bio.en||[]).map(p=>`<p>${escape(p)}</p>`).join('');$('#footer').textContent=`${album.artist} © ${album.year}–${new Date().getFullYear()} · ${c.rights}`;for(const name of ['previous','next'])$(`#${name}`).setAttribute('aria-label',c[name]);$('#seek').setAttribute('aria-label',c.seek);$('#now-label').textContent=`${c.track} ${String(current+1).padStart(2,'0')}`;sync();setTheme(document.body.dataset.theme);}
function sync(){if(!album)return;const playing=!audio.paused;$('#play').innerHTML=svg(playing?'pause':'play');$('#play').setAttribute('aria-label',copy[language][playing?'pause':'play']);$('#now-title').textContent=album.tracks[current].title;$('#now-label').textContent=`${copy[language].track} ${String(current+1).padStart(2,'0')}`;document.querySelectorAll('.track').forEach((el,i)=>{el.setAttribute('aria-current',String(i===current));el.querySelector('.track-number').textContent=i===current&&playing?'▶':String(i+1).padStart(2,'0');});}
function progress(){const duration=audio.duration||album.tracks[current].duration;$('#elapsed').textContent=time(audio.currentTime);$('#duration').textContent=time(duration);$('#seek').value=Number.isFinite(duration)&&duration>0?audio.currentTime/duration*100:0;$('#seek').setAttribute('aria-valuetext',`${time(audio.currentTime)} / ${time(duration)}`);}
async function play(){if(!loaded){audio.src=safeUrl(album.tracks[current].src);loaded=true;}$('#play-error').hidden=true;try{await audio.play();}catch(e){if(e.name!=='AbortError'){$('#play-error').textContent=copy[language].error;$('#play-error').hidden=false;}}sync();}
function select(index,autoplay=true){audio.pause();current=(index+album.tracks.length)%album.tracks.length;loaded=false;audio.removeAttribute('src');audio.load();sync();progress();if('mediaSession' in navigator){navigator.mediaSession.metadata=new MediaMetadata({title:album.tracks[current].title,artist:album.artist,album:album.title,artwork:[{src:safeUrl(album.cover)}]});}if(autoplay)play();}
function render(){document.title=`${album.artist} — ${album.title}`;document.documentElement.style.setProperty('--accent',/^#[0-9a-f]{6}$/i.test(album.accent)?album.accent:'#4fbe85');$('meta[name=description]').content=`${album.artist} — ${album.title} (${album.year}). Listen to the complete release.`;$('#main').innerHTML=`<section class="release" aria-label="${escape(album.title)}"><div class="artwork"><img class="cover" src="${escape(safeUrl(album.cover))}" alt="${escape(album.title)} album cover" width="600" height="600"><div class="cover-note"><span>${escape(album.year)} · ${escape(album.type)}</span><span>${album.tracks.length} TRACKS · ${time(album.tracks.reduce((s,t)=>s+t.duration,0))}</span></div></div><div><p class="eyebrow">${escape(album.year)} / ${escape(album.type)}</p><h1 class="artist">${escape(album.artist)}</h1><p class="album-title">${escape(album.title)}</p><div class="player"><div class="transport"><button id="play" class="control play"></button><div class="now"><small id="now-label"></small><strong id="now-title"></strong></div><button id="previous" class="control">${svg('previous')}</button><button id="next" class="control">${svg('next')}</button></div><div class="timeline"><time id="elapsed">0:00</time><input id="seek" type="range" min="0" max="100" step="0.1" value="0"><time id="duration">0:00</time></div><p class="play-error" id="play-error" role="alert" hidden></p></div><ol class="tracklist">${album.tracks.map((t,i)=>`<li><button class="track" data-index="${i}" aria-label="${escape(copy[language].play+' '+t.title)}"><span class="track-number">${String(i+1).padStart(2,'0')}</span><span class="track-name">${escape(t.title)}</span><span class="track-duration">${time(t.duration)}</span></button></li>`).join('')}</ol></div></section><section class="details"><div><h2 id="bio-heading" class="section-heading"></h2><div id="bio" class="bio"></div></div><div><h2 id="members-heading" class="section-heading"></h2><ul class="members">${album.members.map(m=>`<li>${escape(m.name)}<span>${escape(m.roles)}</span></li>`).join('')}</ul><h2 id="links-heading" class="section-heading" style="margin-top:28px"></h2><nav class="links">${album.links.map(l=>`<a href="${escape(safeUrl(l.url))}" target="_blank" rel="noopener noreferrer">${escape(l.label)}</a>`).join('')}</nav></div></section>`;
$('#main').setAttribute('aria-busy','false');$('#play').onclick=()=>audio.paused?play():audio.pause();$('#previous').onclick=()=>select(current-1);$('#next').onclick=()=>select(current+1);document.querySelectorAll('.track').forEach(el=>el.onclick=()=>Number(el.dataset.index)===current?(audio.paused?play():audio.pause()):select(Number(el.dataset.index)));$('#seek').oninput=()=>{if(loaded&&Number.isFinite(audio.duration))audio.currentTime=Number($('#seek').value)/100*audio.duration;progress();};details();select(0,false);}
for(const event of ['play','pause','ended'])audio.addEventListener(event,sync);
for(const event of ['timeupdate','durationchange','loadedmetadata'])audio.addEventListener(event,()=>{if(album)progress();});
audio.addEventListener('ended',()=>select(current+1));audio.addEventListener('error',()=>{if(album&&loaded){$('#play-error').textContent=copy[language].error;$('#play-error').hidden=false;}});
$('#language').onchange=()=>{language=$('#language').value;preference('recordplayer-language',language);details();document.querySelectorAll('.track').forEach((el,i)=>el.setAttribute('aria-label',copy[language].play+' '+album.tracks[i].title));};
document.addEventListener('keydown',e=>{if(!album||e.altKey||e.ctrlKey||e.metaKey||e.shiftKey||e.target.closest('input,select,button,a,textarea,[contenteditable]'))return;if(['Space','ArrowRight','ArrowLeft'].includes(e.code))e.preventDefault();if(e.code==='Space')audio.paused?play():audio.pause();if(e.code==='ArrowRight')select(current+1);if(e.code==='ArrowLeft')select(current-1);});
try{const response=await fetch(catalogUrl);if(!response.ok)throw new Error('Catalog unavailable');const catalog=await response.json();const id=new URLSearchParams(location.search).get('albumId')||catalog.defaultAlbum;album=catalog.albums[id];if(!album||!album.tracks?.length){album=null;$('#main').innerHTML=`<div class="error"><h1>Record not found</h1><p>Choose a release:</p>${Object.entries(catalog.albums).map(([key,a])=>`<p><a href="?albumId=${encodeURIComponent(key)}">${escape(a.artist)} — ${escape(a.title)}</a></p>`).join('')}</div>`;$('#main').setAttribute('aria-busy','false');$('#language').disabled=true;}else{language=preference('recordplayer-language')||(navigator.language.startsWith('it')?'it':'en');if(!copy[language])language='en';$('#language').value=language;render();if('mediaSession' in navigator){navigator.mediaSession.setActionHandler('play',play);navigator.mediaSession.setActionHandler('pause',()=>audio.pause());navigator.mediaSession.setActionHandler('previoustrack',()=>select(current-1));navigator.mediaSession.setActionHandler('nexttrack',()=>select(current+1));}}}catch(e){album=null;$('#main').setAttribute('aria-busy','false');$('#main').innerHTML='<div class="error"><h1>Unable to load this record</h1><p>Please try reloading the page.</p></div>';$('#language').disabled=true;console.error(e);}
